[package]
name = "batch_cog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdal = {version = "0.16.0", features = ["bindgen"]}
rayon = "1.10.0"
